import Head from "next/head";
import Image from "next/image";
import { Container, Box, Grid, Typography } from "@mui/material";
import styles from "../styles/Home.module.css";

import type { NextPage } from "next";

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid
        container
        justifyContent="center"
        alignItems="center"
        sx={{ minHeight: "100vh" }}
      >
        <Grid item xs={12}>
          <Typography variant="h1" align="center">
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </Typography>

          <Typography variant="body1" align="center">
            Get started by editing{" "}
            <code className={styles.code}>pages/index.tsx</code>
          </Typography>
        </Grid>
      </Grid>
    </Container>
  );
};

export default Home;
